**라이브러리결과값 vs 직접 Numpy로 미분**

In [34]:
import numpy as np
from sklearn.linear_model import LogisticRegression

# 학습 데이터셋 정의
X_train = np.array([[6], [5], [4], [3], [2], [1]])
y_train = np.array([1, 1, 1, 0, 0, 0])

# 모델 생성 및 학습
clf = LogisticRegression()
clf.fit(X_train, y_train)

# 확률값과 클래스 예측
X_test = np.array([[4.5], [1.5]])
proba = clf.predict_proba(X_test)
y_pred = np.where(proba[:, 1] > 0.3, 1, 0)  # 임계값을 0.3으로 낮춤

# 결과 출력
print(f"확률값: {proba}")
print(f"예측 결과: {y_pred}")

확률값: [[0.24589705 0.75410295]
 [0.9038899  0.0961101 ]]
예측 결과: [1 0]


In [2]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def compute_cost(theta, X, y):
    h = sigmoid(X.dot(theta))
    cost = (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()
    return cost

def gradient_descent(theta, X, y, alpha, epochs):
    m = len(y)
    J_history = []

    for i in range(epochs):
        h = sigmoid(X.dot(theta))
        theta = theta - alpha * (1 / m) * (X.T.dot(h - y))
        J_history.append(compute_cost(theta, X, y))

    return theta, J_history

In [38]:
# 데이터 정의
X_train = np.array([[6], [5], [4], [3], [2], [1]])
X_train = np.hstack([X_train,np.ones((6, 1))])

y_train = np.array([1, 1, 1, 0, 0, 0])

print(X_train)
print(y_train)

# 모델 학습
theta = np.zeros((2, 1))
alpha = 0.1
epochs = 100
theta, J_history = gradient_descent(theta, X_train, y_train, alpha, epochs)

# 예측
X_test = np.array([[4.5], [1.5]])
X_test = np.hstack([X_test,np.ones((2, 1))])
print(X_test)
proba = sigmoid(X_test.dot(theta))
print(proba)
y_pred = np.where(proba > 0.3, 1, 0)

# 결과 출력
print(f"확률값: {proba}")
print(f"예측 결과: {y_pred}")

[[6. 1.]
 [5. 1.]
 [4. 1.]
 [3. 1.]
 [2. 1.]
 [1. 1.]]
[1 1 1 0 0 0]
[[4.5 1. ]
 [1.5 1. ]]
[[0.99885583 0.99885583 0.99885583 0.00114417 0.00114417 0.00114417]
 [0.936865   0.936865   0.936865   0.063135   0.063135   0.063135  ]]
확률값: [[0.99885583 0.99885583 0.99885583 0.00114417 0.00114417 0.00114417]
 [0.936865   0.936865   0.936865   0.063135   0.063135   0.063135  ]]
예측 결과: [[1 1 1 0 0 0]
 [1 1 1 0 0 0]]


In [40]:
print(X_test.shape)
print(theta.shape)

proab = [ 
    [0.7 ,0.9, 0.9, 0.001, 0.001, 0.00114417] , 
    [0.9 ,0.9, 0.9, 0.06 , 0.063, 0.063135  ]
]
print(proba)
y_pred = np.where(proba > 0.3, 1, 0)
print(y_pred)
print(theta.shape)

(2, 2)
(2, 6)
[[0.99885583 0.99885583 0.99885583 0.00114417 0.00114417 0.00114417]
 [0.936865   0.936865   0.936865   0.063135   0.063135   0.063135  ]]
[[1 1 1 0 0 0]
 [1 1 1 0 0 0]]
(2, 6)
