In [2]:
# 공식 문서 
# https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_.html#torch.Tensor.scatter_

# src 텐서 안의 value를 scatter 하는것이다.
# src 텐서를 돌면서 input 텐서안에 그것들의 위치를 찾아서 고침

In [5]:
# Graphical Diagram for dim = 0
# https://yuyangyy.medium.com/understand-torch-scatter-b0fd6275331c

import torch
import numpy as np

src = torch.from_numpy(np.arange(1, 11)).float().view(2, 5)
input_tensor = torch.zeros(3, 5)
index_tensor = torch.tensor(
    [[0, 1, 2, 0, 0], 
     [2, 0, 0, 1, 2]]
)
dim = 0

print(input_tensor.scatter_(dim, index_tensor, src))
# input tensor 는 변화할 값이니 일단두고 
# src 와 index 의 관계가 너무 궁금하다...

# dim = 0 일시 index tensor 에서의 value 는 row index 를 나타낸다.
# 여기서 알수있는 사실은 
# index tensor 의 max value 는 input row 의 갯수보다 작다. 

# 1 2 3 4 5 
# 6 7 8 9 10 
# 에서 1 ,6  =>  0,2
#      2, 7  =>  1,0 등으로 각각 옮겨줌


tensor([[ 1.,  7.,  8.,  4.,  5.],
        [ 0.,  2.,  0.,  9.,  0.],
        [ 6.,  0.,  3.,  0., 10.]])


In [6]:
# Graphical Diagram for dim = 1
# https://yuyangyy.medium.com/understand-torch-scatter-b0fd6275331c

src = torch.from_numpy(np.arange(1, 11)).float().view(2, 5)
input_tensor = torch.zeros(3, 5)
index_tensor = torch.tensor([[3, 0, 2, 1, 4], [2, 0, 1, 3, 1]])
dim = 1
print(input_tensor.scatter_(dim, index_tensor, src))

# src의 1번열은  1, 2, 3, 4, 5 
# index 의       3  0  2  1 4 에 맞춰서
# 1은 3열, 2는 0열 3은 2열 이런식으로 맞춘다...

tensor([[ 2.,  4.,  3.,  1.,  5.],
        [ 7., 10.,  6.,  9.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])


In [7]:
# Graphical Diagram for a Trickier Example 

# src = value 이고 
# size of the index tensor < input tensor dimension

input_tensor = torch.from_numpy(np.arange(1, 16)).float().view(3, 5) # dim is 2
# unsqueeze to have dim = 2
index_tensor = torch.tensor([4, 0, 1]).unsqueeze(1) 
print(index_tensor)
src = 0 # use broadcasted version which has same size as the index tensor
dim = 1 # scatter
print(input_tensor.scatter_(dim, index_tensor, src))

tensor([[4],
        [0],
        [1]])
tensor([[ 1.,  2.,  3.,  4.,  0.],
        [ 0.,  7.,  8.,  9., 10.],
        [11.,  0., 13., 14., 15.]])


In [9]:
# 개인수행
# 그렇다면 scatter 를 이용하여 one-hot vector 를 표현하는 방법은?

input_tensor = torch.zeros(3, 5)
index_tensor = torch.tensor([4, 0, 1]).unsqueeze(1)
src = 1
dim = 1

print(input_tensor.scatter_(dim, index_tensor, src))

tensor([[0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]])
