In [36]:
# https://stackoverflow.com/questions/73698041/how-retain-grad-in-pytorch-works-i-found-its-position-changes-the-grad-result

import torch
a = torch.tensor([1.], requires_grad=True)
y = torch.zeros((6)) 
gt = torch.zeros((6))

y[0] = a
y[1] = y[0] * 2
y.retain_grad()
loss = torch.sum((y-gt) ** 2)
loss.backward()
print(y.grad)
print(a.grad)

tensor([2., 4., 0., 0., 0., 0.])
tensor([10.])


In [8]:
import torch
a = torch.tensor([1.], requires_grad=True)
y = torch.zeros((10))
gt = torch.zeros((10))

y[0] = a
print(y)
y.retain_grad()
y[1] = y[0] * 2
print(y)
print(y[0])
print(y[1])
print(y[3])

loss = torch.sum((y-gt) ** 2)
loss.backward()
print(y.grad)

tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], grad_fn=<CopySlices>)
tensor([1., 2., 0., 0., 0., 0., 0., 0., 0., 0.], grad_fn=<CopySlices>)
tensor(1., grad_fn=<SelectBackward0>)
tensor(2., grad_fn=<SelectBackward0>)
tensor(0., grad_fn=<SelectBackward0>)
tensor([10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
